//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppFabric.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shveikaDBEntities : DbContext
    {
        public shveikaDBEntities()
            : base("name=shveikaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cloth> cloth { get; set; }
        public virtual DbSet<color> color { get; set; }
        public virtual DbSet<compound> compound { get; set; }
        public virtual DbSet<fittings> fittings { get; set; }
        public virtual DbSet<fittingsItem> fittingsItem { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderedItems> orderedItems { get; set; }
        public virtual DbSet<picture> picture { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<roll> roll { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<storageFittings> storageFittings { get; set; }
        public virtual DbSet<storageRoll> storageRoll { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
